# Generated by Django 5.1.3 on 2024-11-25 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_frontpage', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(default='Anónimo', max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
